name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
projects: ["K4ryuu/8"]
assignees:
  - K4ryuu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below with as much detail as possible.

        ---

        💖 **I automatically detect GitHub Sponsors!**
        Sponsors are automatically labeled. Priority support is available from the **$15/month tier** and above. [Become a Sponsor](https://github.com/sponsors/K4ryuu)

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Significant impact on functionality
        - Critical - Blocking issue, immediate attention required
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is. Include any logs, screenshots, or additional information that may help.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and confirmed this is not a duplicate
          required: true
        - label: I have included all necessary information to reproduce and fix this bug
          required: true